(switch-to-buffer "*Messages*")
(split-window-horizontally)
(split-window-vertically)
(split-window-horizontally)
(other-window 1)
(switch-to-buffer "*scratch*")
(other-window 1)
(dired "~/")
(other-window 1)
